    CREATE SEQUENCE ADMINISTRADOR_SEQ
        START WITH 1
        INCREMENT BY 1
        NOCACHE
        NOCYCLE;
    CREATE TABLE TBL_ADMINISTRADORES(
        ID INTEGER DEFAULT ADMINISTRADOR_SEQ.NEXTVAL NOT NULL
        EMAIL VARCHAR(100) NOT NULL,
        SENHA VARCHAR(10) NOT NULL
    );