CREATE SEQUENCE MORADOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_MORADORES (
    ID INTEGER DEFAULT MORADOR_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);
