CREATE SEQUENCE VEICULOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_VEICULOS (
    ID INTEGER DEFAULT VEICULOS_SEQ.NEXTVAL NOT NULL,
    PLACA VARCHAR(7) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    COR VARCHAR(50) NOT NULL,
    AUTORIZADO BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);
